name: aios-consciousness
channels:
  - conda-forge
  - defaults
  - pytorch
  - nvidia
dependencies:
  # Core Python Environment
  - python=3.11  # Stable version for maximum compatibility
  - pip>=23.0
  - setuptools>=68.0
  - wheel>=0.40
  
  # Scientific Computing & AI Foundation
  - numpy>=1.24.0,<2.0
  - pandas>=2.0.0,<2.1
  - scipy>=1.10.0,<1.12
  - scikit-learn>=1.3.0,<1.4
  
  # Deep Learning & AI Core
  - pytorch>=2.0.0,<2.1
  - torchvision>=0.15.0,<0.16
  - torchaudio>=2.0.0,<2.1
  - transformers>=4.30.0,<4.40
  - tokenizers>=0.13.0,<0.15
  
  # Web & Networking Infrastructure
  - flask>=2.3.0,<3.0
  - requests>=2.31.0,<3.0
  - fastapi>=0.100.0,<0.110
  - uvicorn>=0.22.0,<0.30
  - websockets>=11.0.0,<12.0
  
  # Data Visualization & Analysis
  - matplotlib>=3.7.0,<3.9
  - seaborn>=0.12.0,<0.14
  - plotly>=5.15.0,<6.0
  - graphviz>=0.20.0,<0.25
  - bokeh>=3.2.0,<3.4
  
  # Code Analysis & Development Tools
  - astroid>=2.15.0,<3.0
  - pylint>=2.17.0,<3.0
  - black>=23.3.0,<24.0
  - mypy>=1.4.0,<1.8
  - pytest>=7.4.0,<8.0
  - pytest-asyncio>=0.21.0,<0.25
  
  # Documentation & Knowledge Management
  - sphinx>=7.1.0,<8.0
  - sphinx-rtd-theme>=1.2.0,<2.0
  - mkdocs>=1.5.0,<2.0
  - mkdocs-material>=9.1.0,<10.0
  
  # Additional Dependencies via pip (for packages not available in conda)
  - pip:
    # Advanced AI & Language Models
    - openai>=0.27.0,<1.0
    - anthropic>=0.3.0,<0.5
    - langchain>=0.0.200,<0.1.0
    - chromadb>=0.4.0,<0.5
    - sentence-transformers>=2.2.0,<3.0
    
    # Advanced Code Analysis & Mutation
    - ast-unparse>=1.6.0,<2.0
    - rope>=1.8.0,<2.0
    - jedi>=0.18.0,<0.20
    - libcst>=1.0.0,<2.0
    - parso>=0.8.0,<0.9
    
    # Async & Concurrency Framework
    - aiohttp>=3.8.0,<4.0
    - aiofiles>=23.1.0,<24.0
    - trio>=0.22.0,<0.25
    - anyio>=3.7.0,<4.0
    
    # Quantum Computing & Scientific Extensions
    - qiskit>=0.43.0,<1.0
    - cirq>=1.1.0,<2.0
    - pennylane>=0.31.0,<0.35
    - sympy>=1.12,<2.0
    - mpmath>=1.3.0,<2.0
    
    # Network & Communication Protocols
    - pyzmq>=25.0.0,<26.0
    - msgpack>=1.0.0,<2.0
    - protobuf>=4.23.0,<5.0
    - redis>=4.6.0,<5.0
    
    # System Integration & Monitoring
    - psutil>=5.9.0,<6.0
    - watchdog>=3.0.0,<4.0
    - rich>=13.4.0,<14.0
    - click>=8.1.0,<9.0
    - typer>=0.9.0,<1.0
    
    # Enhanced Type System & Serialization
    - typing-extensions>=4.7.0,<5.0
    - pydantic>=2.0.0,<3.0
    - attrs>=23.1.0,<24.0
    - msgspec>=0.18.0,<0.20
    - orjson>=3.9.0,<4.0
    
    # Natural Language Processing for Consciousness
    - spacy>=3.6.0,<4.0
    - nltk>=3.8.0,<4.0
    - textblob>=0.17.0,<0.18
    
    # Graph Processing & Network Analysis
    - networkx>=3.1,<4.0
    - igraph>=0.10.0,<0.12
    - python-louvain>=0.16,<0.17
    
    # Time Series & Statistical Analysis
    - statsmodels>=0.14.0,<0.15
    - prophet>=1.1.0,<1.2
    
    # Image Processing & Computer Vision
    - pillow>=10.0.0,<11.0
    - opencv-python>=4.8.0,<5.0
    - scikit-image>=0.21.0,<0.23
    
    # Development & Testing Extensions
    - pytest-cov>=4.1.0,<5.0
    - hypothesis>=6.82.0,<7.0
    - autopep8>=2.0.0,<3.0
    - isort>=5.12.0,<6.0
    - flake8>=6.0.0,<7.0
